# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1da2b57ea13c312b25b7ff5d7bbf0827fe0a94924a55b17d509ad4b62da2b8fe437c53810e5647255b91424ec805b100c512c282207c60d6db95b5a5cd11e16e

test:
  secret_key_base: 5c9f69b440ef9cf19eb824ed018468c047503d08e472c89310e149b69dd02d68417a2d8b5695a37b60ee64284ef0cf85c75f9e0b552586cc2de925d278641d56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
